---
- name: Deploy VOD NFV on Kubernetes
  hosts: all
  tasks:
    # - name: Run minikube status comamnd
    #   shell: minikube status
    #   register: minikube_status
    # - debug:
    #     msg: "{{ minikube_status.stdout }}"
    - name: Setting Ingress from configuration file
      k8s:
        state: present
        src: "{{ lookup('env', 'WORKSPACE') }}/deploy-kubernetes/nginx-ingress.yml"
    - name: Setting Service from configuration file
      k8s:
        state: present
        src: "{{ lookup('env', 'WORKSPACE') }}/deploy-kubernetes/server-cluster-service.yml"
    - name: Setting Deployment from configuration file
      k8s:
        state: present
        src: "{{ lookup('env', 'WORKSPACE') }}/deploy-kubernetes/server-deployment.yml"
    
  