---
- name: Deploy VOD NFV on Kubernetes
  hosts: all
  tasks:
    - name: Copy all the configuration files to the target
      copy:
        src: "deploy-kubernetes"
        dest: "~/"
    - name: Applying Kubernetes configuration file
      command: kubectl apply -f deploy-kubernetes/