- name: Deploy VOD NFV on Kubernetes
  hosts: all
  tasks:
    - name: Setting Ingress from configuration file
      k8s:
        state: present
        src: "{{ lookup('env', 'WORKSPACE') }}/deploy-kubernetes/nginx-ingress.yml"
    - name: Setting Service from configuration file
      k8s:
        state: present
        src: "{{ lookup('env', 'WORKSPACE') }}/deploy-kubernetes/server-cluster-service.yml"
    - name: Setting Deployment from configuration file
      k8s:
        state: present
        src: "{{ lookup('env', 'WORKSPACE') }}/deploy-kubernetes/server-deployment.yml"